name: SRP
on:
  workflow_dispatch:
  
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Install Google Chrome version 106
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          sudo apt-get install -y libnss3 libgconf-2-4
          curl -o chromedriver.zip "https://chromedriver.storage.googleapis.com/106.0.6538.69/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: |
          mvn test
