name: SRP
on:
  schedule:
    - cron: '*/11 * * * 0-6'
  
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '20' # Update Node.js version to 20

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Set up Maven
        run: |
          sudo apt-get install -y maven
          
      - name: Build with Maven
        run: |
          mvn test
